name: Test

on: pull_request

jobs:
  lint:
    if: github.ref != 'refs/heads/renovate/*'
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  test:
    runs-on: dind
    steps:
      - uses: actions/checkout@v4
      - name: Get docker tags
        id: tags
        shell: sh
        env:
          CUSTOM_TAGS: "latest"
          IMAGE_NAME: "mwalbeck/flox"
        run: |
          determine-docker-tags
          dockerd &
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
      - name: Test build
        uses: https://github.com/docker/build-push-action@v6
        with:
          tags: ${{ steps.tags.outputs.tags }}
